# active spring boot profile
spring:
   profiles:
      # default: dev
      active: dev

---

# common - spring configuration
spring:
   # devtools - live reload
   devtools:
      livereload:
         enabled: true

   # mvc
   mvc:
      view:
         prefix: /WEB-INF/views/
         suffix: .jsp

   # message resource(Internationalization)
   messages:
      always-user-message-format: true
      basename: messages/messages_ko
      encoding: utf-8

   # multipart
   servlet:
      multipart:
         enabled: true
         max-file-size: 50MB
         max-request-size: 50MB

   # aop(@EnableAspectJAutoProxy)
   aop:
      auto: true
      proxy-target-class: true

---

# dev profile - spring boot configuration
spring:
   config:
      active:
         on-profile: dev

   # datasource
   datasource:
      username: webdb
      password: webdb
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/webdb?characterEncoding=utf8
      hikari:
         minimum-idle: 10
         maximum-pool-size: 20

---

# production profile - spring boot configuration
spring:
   config:
      active:
         on-profile: production
   # datasource
   datasource:
      username: webdb
      password: pikaaaaachuuuuuuuuuu@@
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://222.3.4.5:3306/webdb?characterEncoding=utf8
      hikari:
         minimum-idle: 100
         maximum-pool-size: 200

---

# server
server:
   port: 8080
   servlet:
      context-path: /mysite06
   encoding:
      charset: utf-8
      enabed: true
      force: false
      force-request: false
      force-response: false

---
---
---
---

# mybatis
mybatis:
   config-location: classpath:mybatis/configuration.xml

---

# logging
logging:
   config: classpath:logback.xml
